name: Neptune actions

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  compare-experiments:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - env:
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
          NEPTUNE_PROJECT_NAME: ${{ secrets.NEPTUNE_PROJECT_NAME }}
      - name: Get Neptune Experiments

        id: compare
        run: |
          pip install neptune-client
          python get_neptune_experiments.py
          result=$(cat comparison_table.md)
          echo ::set-output name=result::$result

      - name: Create a comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            ${{ steps.compare.outputs.result }}
