name: Compare Neptune experiments

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  compare-experiments:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Neptune Experiments
        run: pip install neptune-client
        run: python get_neptune_experiments.py

      - name: Create a comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown**
            - Created by [commit-comment][1]
