name: Neptune actions

on:
  pull_request:
    branches: [master]

jobs:
  compare-experiments:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    env:
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
      NEPTUNE_PROJECT_NAME: ${{ secrets.NEPTUNE_PROJECT_NAME }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout pull request branch
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Setup pull request branch environment and run experiment
        id: experiment_pr
        run: |
          pip install -r requirements.txt
          python train.py
          experiment_id=$(cat experiment_id.txt)
          echo ::set-output name=experiment_id::$experiment_id

      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup main branch environment and run experiment
        id: experiment_main
        run: |
          pip install -r requirements.txt
          python train.py
          experiment_id=$(cat experiment_id.txt)
          echo ::set-output name=experiment_id::$experiment_id

      - name: Get Neptune experiments
        env:
          MAIN_BRANCH_REF: ${{ steps.experiment_main.outputs.github_ref }}
          MAIN_BRANCH_EXPERIMENT_ID: ${{ steps.experiment_main.outputs.experiment_id }}
          PR_BRANCH_REF: ${{ steps.experiment_pr.outputs.github_ref }}
          PR_BRANCH_EXPERIMENT_ID: ${{ steps.experiment_pr.outputs.experiment_id }}
        id: compare
        run: |
          pip install -r requirements.txt
          python -m create_github_actions_comment \
            --api_token $NEPTUNE_API_TOKEN \
            --project_name $NEPTUNE_PROJECT_NAME \
            --experiment_ids $MAIN_BRANCH_EXPERIMENT_ID $PR_BRANCH_EXPERIMENT_ID \
            --filepath comment_body.md
          result=$(cat comment_body.md)
          echo ::set-output name=result::$result

      - name: Create a comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            ${{ steps.compare.outputs.result }}
