name: Neptune actions

on:
  push:
    branches: [master]
  repository_dispatch:

jobs:
  compare-experiments:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    env:
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
      NEPTUNE_PROJECT_NAME: ${{ secrets.NEPTUNE_PROJECT_NAME }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup main branch environment and run experiment
        id: experiment_main
        run: |
          pip install -r requirements.txt
          export NEPTUNE_EXPERIMENT_TAG_ID=$(uuidgen)
          python train.py
          echo ::set-output name=experiment_tag_id::$NEPTUNE_EXPERIMENT_TAG_ID
          
      - name: PING - Dispatch initiating repository event
        run: |
          curl -X POST https://api.github.com/repos/Data-Science-Squad/dssquad-ml/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
